<?php

return $state_zipcodes = array(
	array(
		'title' => 'Alaska',
		'code'  => 'AK',
		'min'   => '99501',
		'max'   => '99950',
	),
	array(
		'title' => 'Alabama',
		'code'  => 'AL',
		'min'   => '35004',
		'max'   => '36925',
	),
	array(
		'title' => 'Arkansas',
		'code'  => 'AR',
		'min'   => '71601',
		'max'   => '72959',
	),
	array(
		'title' => 'Arkansas( Texarkana )',
		'code'  => 'AR',
		'min'   => '75502',
		'max'   => '75502',
	),
	array(
		'title' => 'Arizona',
		'code'  => 'AZ',
		'min'   => '85001',
		'max'   => '86556',
	),
	array(
		'title' => 'California',
		'code'  => 'CA',
		'min'   => '90001',
		'max'   => '96162',
	),
	array(
		'title' => 'Colorado',
		'code'  => 'CO',
		'min'   => '80001',
		'max'   => '81658',
	),
	array(
		'title' => 'Connecticut',
		'code'  => 'CT',
		'min'   => '6001',
		'max'   => '6389',
	),
	array(
		'title' => 'Connecticut',
		'code'  => 'CT',
		'min'   => '6401',
		'max'   => '6928',
	),
	array(
		'title' => 'Dist of Columbia',
		'code'  => 'DC',
		'min'   => '20001',
		'max'   => '20039',
	),
	array(
		'title' => 'Dist of Columbia',
		'code'  => 'DC',
		'min'   => '20042',
		'max'   => '20599',
	),
	array(
		'title' => 'Dist of Columbia',
		'code'  => 'DC',
		'min'   => '20799',
		'max'   => '20799',
	),
	array(
		'title' => 'Delaware',
		'code'  => 'DE',
		'min'   => '19701',
		'max'   => '19980',
	),
	array(
		'title' => 'Florida',
		'code'  => 'FL',
		'min'   => '32004',
		'max'   => '34997',
	),
	array(
		'title' => 'Georgia',
		'code'  => 'GA',
		'min'   => '30001',
		'max'   => '31999',
	),
	array(
		'title' => 'Georga( Atlanta )',
		'code'  => 'GA',
		'min'   => '39901',
		'max'   => '39901',
	),
	array(
		'title' => 'Hawaii',
		'code'  => 'HI',
		'min'   => '96701',
		'max'   => '96898',
	),
	array(
		'title' => 'Iowa',
		'code'  => 'IA',
		'min'   => '50001',
		'max'   => '52809',
	),
	array(
		'title' => 'Iowa( OMAHA )',
		'code'  => 'IA',
		'min'   => '68119',
		'max'   => '68120',
	),
	array(
		'title' => 'Idaho',
		'code'  => 'ID',
		'min'   => '83201',
		'max'   => '83876',
	),
	array(
		'title' => 'Illinois',
		'code'  => 'IL',
		'min'   => '60001',
		'max'   => '62999',
	),
	array(
		'title' => 'Indiana',
		'code'  => 'IN',
		'min'   => '46001',
		'max'   => '47997',
	),
	array(
		'title' => 'Kansas',
		'code'  => 'KS',
		'min'   => '66002',
		'max'   => '67954',
	),
	array(
		'title' => 'Kentucky',
		'code'  => 'KY',
		'min'   => '40003',
		'max'   => '42788',
	),
	array(
		'title' => 'Louisiana',
		'code'  => 'LA',
		'min'   => '70001',
		'max'   => '71232',
	),
	array(
		'title' => 'Louisiana',
		'code'  => 'LA',
		'min'   => '71234',
		'max'   => '71497',
	),
	array(
		'title' => 'Massachusetts',
		'code'  => 'MA',
		'min'   => '1001',
		'max'   => '2791',
	),
	array(
		'title' => 'Massachusetts( Andover )',
		'code'  => 'MA',
		'min'   => '5501',
		'max'   => '5544',
	),
	array(
		'title' => 'Maryland',
		'code'  => 'MD',
		'min'   => '20331',
		'max'   => '20331',
	),
	array(
		'title' => 'Maryland',
		'code'  => 'MD',
		'min'   => '20335',
		'max'   => '20797',
	),
	array(
		'title' => 'Maryland',
		'code'  => 'MD',
		'min'   => '20812',
		'max'   => '21930',
	),
	array(
		'title' => 'Maine',
		'code'  => 'ME',
		'min'   => '3901',
		'max'   => '4992',
	),
	array(
		'title' => 'Michigan',
		'code'  => 'MI',
		'min'   => '48001',
		'max'   => '49971',
	),
	array(
		'title' => 'Minnesota',
		'code'  => 'MN',
		'min'   => '55001',
		'max'   => '56763',
	),
	array(
		'title' => 'kc96 DataMO',
		'code'  => 'MO',
		'min'   => '63001',
		'max'   => '65899',
	),
	array(
		'title' => 'Mississippi',
		'code'  => 'MS',
		'min'   => '38601',
		'max'   => '39776',
	),
	array(
		'title' => 'Mississippi( Warren )',
		'code'  => 'MS',
		'min'   => '71233',
		'max'   => '71233',
	),
	array(
		'title' => 'Montana',
		'code'  => 'MT',
		'min'   => '59001',
		'max'   => '59937',
	),
	array(
		'title' => 'North Carolina',
		'code'  => 'NC',
		'min'   => '27006',
		'max'   => '28909',
	),
	array(
		'title' => 'North Dakota',
		'code'  => 'ND',
		'min'   => '58001',
		'max'   => '58856',
	),
	array(
		'title' => 'Nebraska',
		'code'  => 'NE',
		'min'   => '68001',
		'max'   => '68118',
	),
	array(
		'title' => 'Nebraska',
		'code'  => 'NE',
		'min'   => '68122',
		'max'   => '69367',
	),
	array(
		'title' => 'new Hampshire',
		'code'  => 'NH',
		'min'   => '3031',
		'max'   => '3897',
	),
	array(
		'title' => 'new Jersey',
		'code'  => 'NJ',
		'min'   => '7001',
		'max'   => '8989',
	),
	array(
		'title' => 'new Mexico',
		'code'  => 'NM',
		'min'   => '87001',
		'max'   => '88441',
	),
	array(
		'title' => 'Nevada',
		'code'  => 'NV',
		'min'   => '88901',
		'max'   => '89883',
	),
	array(
		'title' => 'new York ( Fishers Is)',
		'code'  => 'NY',
		'min'   => '6390',
		'max'   => '6390',
	),
	array(
		'title' => 'new York',
		'code'  => 'NY',
		'min'   => '10001',
		'max'   => '14975',
	),
	array(
		'title' => 'Ohio',
		'code'  => 'OH',
		'min'   => '43001',
		'max'   => '45999',
	),
	array(
		'title' => 'Oklahoma',
		'code'  => 'OK',
		'min'   => '73001',
		'max'   => '73199',
	),
	array(
		'title' => 'Oklahoma',
		'code'  => 'OK',
		'min'   => '73401',
		'max'   => '74966',
	),
	array(
		'title' => 'Oregon',
		'code'  => 'or',
		'min'   => '97001',
		'max'   => '97920',
	),
	array(
		'title' => 'Pennsylvania',
		'code'  => 'PA',
		'min'   => '15001',
		'max'   => '19640',
	),
	array(
		'title' => 'Puerto Rico',
		'code'  => 'PR',
		'min'   => '0',
		'max'   => '0',
	),
	array(
		'title' => 'Rhode Island',
		'code'  => 'RI',
		'min'   => '2801',
		'max'   => '2940',
	),
	array(
		'title' => 'South Carolina',
		'code'  => 'SC',
		'min'   => '29001',
		'max'   => '29948',
	),
	array(
		'title' => 'South Dakota',
		'code'  => 'SD',
		'min'   => '57001',
		'max'   => '57799',
	),
	array(
		'title' => 'Tennessee',
		'code'  => 'TN',
		'min'   => '37010',
		'max'   => '38589',
	),
	array(
		'title' => 'Texas( Austin )',
		'code'  => 'TX',
		'min'   => '73301',
		'max'   => '73301',
	),
	array(
		'title' => 'Texas',
		'code'  => 'TX',
		'min'   => '75001',
		'max'   => '75501',
	),
	array(
		'title' => 'Texas',
		'code'  => 'TX',
		'min'   => '75503',
		'max'   => '79999',
	),
	array(
		'title' => 'Texas( El Paso)',
		'code'  => 'TX',
		'min'   => '88510',
		'max'   => '88589',
	),
	array(
		'title' => 'Utah',
		'code'  => 'UT',
		'min'   => '84001',
		'max'   => '84784',
	),
	array(
		'title' => 'Virginia',
		'code'  => 'VA',
		'min'   => '20040',
		'max'   => '20041',
	),
	array(
		'title' => 'Virginia',
		'code'  => 'VA',
		'min'   => '20040',
		'max'   => '20167',
	),
	array(
		'title' => 'Virginia',
		'code'  => 'VA',
		'min'   => '20042',
		'max'   => '20042',
	),
	array(
		'title' => 'Virginia',
		'code'  => 'VA',
		'min'   => '22001',
		'max'   => '24658',
	),
	array(
		'title' => 'Vermont',
		'code'  => 'VT',
		'min'   => '5001',
		'max'   => '5495',
	),
	array(
		'title' => 'Vermont',
		'code'  => 'VT',
		'min'   => '5601',
		'max'   => '5907',
	),
	array(
		'title' => 'Washington',
		'code'  => 'WA',
		'min'   => '98001',
		'max'   => '99403',
	),
	array(
		'title' => 'Wisconsin',
		'code'  => 'WI',
		'min'   => '53001',
		'max'   => '54990',
	),
	array(
		'title' => 'West Virginia',
		'code'  => 'WV',
		'min'   => '24701',
		'max'   => '26886',
	),
	array(
		'title' => 'Wyoming',
		'code'  => 'WY',
		'min'   => '82001',
		'max'   => '83128',
	),
);
